run all

diff --git a/run-all-on-pr b/run-all-on-pr
--- a/run-all-on-pr
+++ b/run-all-on-pr
@@ -4,13 +4,41 @@ set -e
 
 cd "$(dirname $0)"
 
-if [ "$1" == "" ] && [ "$(git rev-parse --abbrev-ref HEAD)" == "main" ]; then
-  echo "usage $0 <pr-number>"
+PR_NUMBER=$1
+
+if [ "$(git rev-parse --abbrev-ref HEAD)" != "main" ]; then
+  echo "You are not on main branch. Please switch to main branch and try again."
   exit 1
 fi
 
-if [ "$1" != "" ]; then
-  gh pr checkout $1
+if [ "$1" == "" ]; then
+  # Define color codes
+  YELLOW='\033[1;33m'
+  CYAN='\033[1;36m'
+  GREEN='\033[1;32m'
+  NC='\033[0m' # No Color
+
+  DATA=$(gh pr list --json number,title --jq '.[] | "\(.number) \(.title)"')
+
+  echo -e "${YELLOW}Select a PR to run all on:${NC}"
+  echo "$DATA" | awk -v c="$CYAN" -v nc="$NC" -v g="$GREEN" '{print c NR " - " g $0 nc}'
+  echo -e "${CYAN}0 - Exit${NC}"
+
+  read -ep "Select a PR: " SELECTED_PR
+  if [ "$SELECTED_PR" == "0" ]; then
+    echo "No PR selected. Exiting."
+    exit 1
+  fi
+  if [ "$SELECTED_PR" -lt 1 ]; then
+    echo "Invalid selection. Exiting."
+    exit 1
+  fi
+  SELECTED_PR=$((SELECTED_PR - 1))
+  PR_NUMBER=$(echo "$DATA" | sed -n "${SELECTED_PR}p" | awk '{print $1}')
+fi
+
+if [ "$PR_NUMBER" != "" ]; then
+  gh pr checkout $PR_NUMBER
 fi
 
 npm i
